FROM ubuntu:focal

ENV CXX=/usr/bin/g++ \
    CC=/usr/bin/gcc \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
       sudo \
       binutils \
       wget \
       git \
       libc6-dev \
       g++-10 \
       libgmp-dev \
       libmpfr-dev \
       libmpc-dev \
       nasm \
       dh-autoreconf \
       ninja-build \
       libffi-dev \
       libssl-dev \
       pkg-config \
       subversion \
       zlib1g-dev \
       libbz2-dev \
       libsqlite3-dev \
       libreadline-dev \
       xz-utils \
       curl \
       libncurses5-dev \
       libncursesw5-dev \
       liblzma-dev \
       ca-certificates \
       autoconf-archive \
       libmagic-dev \
       libexiv2-dev \
       libpoco-dev \
       libfmt-dev \
       libspdlog-dev \
       cmake \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 100 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 100 \
    && ln -s /usr/include/locale.h /usr/include/xlocale.h \
    && groupadd 1001 -g 1001 \
    && groupadd 1000 -g 1000 \
    && groupadd 2000 -g 2000 \
    && groupadd 999 -g 999 \
    && useradd -ms /bin/bash bsc -g 1001 -G 1000,2000,999 \
    && printf "bsc:bsc" | chpasswd\
    && cd /tmp && git clone https://github.com/catchorg/Catch2.git && cd Catch2 \
    && cmake -Bbuild -H. -DBUILD_TESTING=OFF \
    && cmake --build build/ --target install \
    && cd /tmp && git clone https://github.com/pantor/inja.git && cd inja \
    && cmake -Bbuild -H. \
    && cmake --build build/ --target install \
    && cd /tmp && git clone https://github.com/USCiLab/cereal.git && cd cereal \
    && cmake -Bbuild -H. -DJUST_INSTALL_CEREAL=ON \
    && cmake --build build/ --target install




USER bsc
WORKDIR /home/bsc
COPY . /home/bsc/

RUN mkdir -p /home/bsc/ \
   && echo "BSC Development Envrionment setup complete" \
