//
// Created by stilgar on 18.10.17.
//

#ifndef BASYCO_JOURNALMETHOD_H
#define BASYCO_JOURNALMETHOD_H

enum JournalMethod {
    ADDED_FILE,
    MODIFIED_FILE,
    DELETED_FILE,
    MOVED_FILE,
    ADDED_DIRECTORY,
    MODIFIED_DIRECTORY,
    DELETED_DIRECTORY,
    MOVED_DIRECTORY,
};


#endif //BASYCO_JOURNALMETHOD_H

